services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    networks:
      - mongo-net

  mongo2:
    image: mongo:latest
    container_name: mongo2
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "rs0", "--port", "27017", "--bind_ip_all"]
    networks:
      - mongo-net

  mongo3:
    image: mongo:latest
    container_name: mongo3
    ports:
      - "27019:27017"
    command: ["mongod", "--replSet", "rs0", "--port", "27017", "--bind_ip_all"]
    networks:
      - mongo-net

  mongo4:
    image: mongo:latest
    container_name: mongo4
    ports:
      - "27125:27017"
    command: ["mongod", "--replSet", "rs0", "--port", "27017", "--bind_ip_all"]
    networks:
      - mongo-net

  mongo5:
    image: mongo:latest
    container_name: mongo5
    ports:
      - "27126:27017"
    command: ["mongod", "--replSet", "rs0", "--port", "27017", "--bind_ip_all"]
    networks:
      - mongo-net

  mongo6:
    image: mongo:latest
    container_name: mongo6
    ports:
      - "27127:27017"
    command: ["mongod", "--replSet", "rs0", "--port", "27017", "--bind_ip_all"]
    networks:
      - mongo-net

  mongo7:
    image: mongo:latest
    container_name: mongo7
    ports:
      - "27128:27017"
    command: ["mongod", "--replSet", "rs0", "--port", "27017", "--bind_ip_all"]
    networks:
      - mongo-net

  mongo8:
    image: mongo:latest
    container_name: mongo8
    ports:
      - "27129:27017"
    command: ["mongod", "--replSet", "rs0", "--port", "27017", "--bind_ip_all"]
    networks:
      - mongo-net

  mongo9:
    image: mongo:latest
    container_name: mongo9
    ports:
      - "27130:27017"
    command: ["mongod", "--replSet", "rs0", "--port", "27017", "--bind_ip_all"]
    networks:
      - mongo-net

  mongo10:
    image: mongo:latest
    container_name: mongo10
    ports:
      - "27131:27017"
    command: ["mongod", "--replSet", "rs0", "--port", "27017", "--bind_ip_all"]
    networks:
      - mongo-net

  mongo11:
    image: mongo:latest
    container_name: mongo11
    ports:
      - "27132:27017"
    command: ["mongod", "--replSet", "rs0", "--port", "27017", "--bind_ip_all"]
    networks:
      - mongo-net

  mongo12:
    image: mongo:latest
    container_name: mongo12
    ports:
      - "27133:27017"
    command: ["mongod", "--replSet", "rs0", "--port", "27017", "--bind_ip_all"]
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge
