services:
  cassandra-1:
    image: cassandra:latest
    container_name: cassandra-1
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_SEEDS: cassandra-1,cassandra-2,cassandra-3
      CASSANDRA_CLUSTER_NAME: ycsb-cluster
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_LISTEN_ADDRESS: cassandra-1
      MAX_HEAP_SIZE: 256M
      HEAP_NEWSIZE: 50M
    networks:
      - cassandra-net
